module.exports = {
  "include": "include definitions",
  "install": "run during compilation",
  "mut": "mutable variable",
  "access": "access mutable fields",
  "unsafe": "file is unsafe",
  "noborrow": "mandatory mutability",
  "noassign": "prevent assignment",
  "nozero": "no zero initialization",
  "noleftover": "mandatory assignment when returned",
  "body": "inline C/C++ code",
  "head": "C/C++ header code",
  "link": "C/C++ linker flags",
  "finally": "C/C++ error code",
  "release": "free all used resources",
  "args": "returns all input arguments",
  "about": "defines documentation",
  "fail": "inline C/C++ code and fail",
  "dynamic": "converts tag to call",
  "invalid": "fails compilation with a message",
};
